kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: otel-demo
  name: jvm-faults
spec:
  schedule: 9 * * * *
  startingDeadlineSeconds: 20
  concurrencyPolicy: Allow
  historyLimit: 1
  type: JVMChaos
  jvmChaos:
    selector:
      namespaces:
        - otel-demo
      labelSelectors:
        app.kubernetes.io/component: adservice
    mode: all
    duration: 15m
    action: stress
    port: 9277
    memType: heap
    name: ''
    value: ''
    exception: ''
    latency: 0
    ruleData: ''
