kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-otel-manager

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-otel-manager
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - chaos-mesh.org
    resources: [ "*" ]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-otel-manager
  namespace: default
subjects:
  - kind: ServiceAccount
    name: account-otel-manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: role-otel-manager
  apiGroup: rbac.authorization.k8s.io
