apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-oteldemo
  namespace: otel-demo
spec:
  hard:
    pods: "50"
    requests.cpu: "5"
    requests.memory: 5Gi
    limits.cpu: "8"
    limits.memory: 10Gi